### ISSUE TITLE
Plugin doesnt unlock DB

### ISSUE THREAD

**Issue by RichardBeisser** [jeremy-bourgin/KeePassAutoUnlock#3]
Hello,

i installed the plugin an set KP-Options as described:
    Security > Advanced > check "Remember master password (in encrypted form) of a database while it is open"
    Integration > check "Run Keepass as Windows startup (current user)"
    Interface > Main Window > check "Minimize to tray instead of taskbar"
    Advanced > Start and exit > check "Start minimized and locked"

So, when logging in in Windows, the plugin unlocks the DB, but because of "Start minimized and locked", the DB gets immediately locked again.
When I open KP from tray, I think the Plugin should autmatically unlock the db, but i got the normal dialog for Masterpassword.

Is there anything I could do?

**Comment by jeremy-bourgin** [comment]
Hello @RichardBeisser, 
I don't have this issue. Have-you configured the plugin ?
You need to go in Tools > KeepassAutoUnlock options > check "Activate plugin" > find the database and enter the password : 
![image](https://user-images.githubusercontent.com/18371022/122685870-72a93900-d20e-11eb-98cd-9d53d1c58e25.png)
![image](https://user-images.githubusercontent.com/18371022/122685906-9ec4ba00-d20e-11eb-8ded-39104782e70e.png)

**Comment by RichardBeisser** [comment]
> 
> 
> Hello @RichardBeisser,
> I don't have this issue. Have-you configured the plugin ?
> You need to go in Tools > KeepassAutoUnlock options > check "Activate plugin" > find the database and enter the password 

Hello,
yes, of course I entered the Master-pw.
If I would not have done this, your Plugin would not login in DB when starting KeePass.
But when DB gets locked (f.ex. when setting option "lock when KP gets minimized"), your plugin cannot unlock a running KP-Instance.
I have to close KP and start it again.

**Comment by jeremy-bourgin** [comment]
Hello @RichardBeisser,

I've the option "Start minimized and locked" activate and the plugin works well. do you have any of these options enabled ? 

![image](https://user-images.githubusercontent.com/18371022/122801876-f7ef2500-d2c4-11eb-819b-72a31cda537b.png)
![image](https://user-images.githubusercontent.com/18371022/122802127-48668280-d2c5-11eb-9caa-a02bc62a2826.png)

**Comment by RichardBeisser** [comment]
yes, i have exactly these 3 options enabled.
Each option locks KeePass, and it seems that your plugin do not unlock workspaces. it can only enter PW when KeePass is starting

**Comment by jeremy-bourgin** [comment]
@RichardBeisser, You need to disable theses options (mostly options in "General").

**Comment by RichardBeisser** [comment]
so your plugin can only unlock Databases while opening?
It cannot unlock Databases which are already open, but locked?

**Comment by jeremy-bourgin** [comment]
@RichardBeisser Yes exactly, because there is no reason to bypass the options in "general"

**Comment by lesensei** [comment]
> @RichardBeisser Yes exactly, because there is no reason to bypass the options in "general"

Hello,
I'm sorry to "hijack" this thread, but I guess I lack some understanding of the innerworkings of KeePass and thought I'd ask here, not for support but to make sure this isn't a feature that would indeed be useful.

The premises of my understanding is that:
- when keepass locks the DB, it purges memory from the master password, so it can't be recovered
- this plugin stores the master password in encrypted form and only deciphers it when unlocking

So the ability to lock the database and to "autounlock" it when reopening from the tray would indeed offer some additional protection (against someone - say, another user of the same computer - that has read access to the memory), while still freeing the user from typing the password (on the premise they are already logged in and they decided it is safe enough that way). This wouldn't "bypass" the options in "general" since they would still be effective while keepass is minimized, adding that little level of security.

At the moment, the only way to make this work is to use triggers (I've tested and confirmed this), but triggers store the pwd in clear in the config file, which is less then ideal compared to what this plugin offers.

Any thoughts on this ?
